### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by thezaff** [aimuzov/LazyVimx#1]
How can I use your config?

**Comment by thezaff** [comment]
upd: I replaced lazyvim with lazyvimx in lazyvim starter lua/config/lazy.lua and in lua/plugins/example.lua
Working well for now, and I like the extras you added :)
I'm new to vim/nvim and lua, so it's really useful for me to use these extras to set up nvim.
Will be happy to contribute as well.

**Comment by aimuzov** [comment]
Thank you, very nice!

I will be glad to receive any feedback.

**Comment by aimuzov** [comment]
I will definitely write instructions, but I don’t have time for that yet.

**Comment by aimuzov** [comment]
@thezaff, can I close this issue?
